Supplemental Digital Content 1 - R Code for Data Processing

library(dplyr)
library(tidyr)
library(rJava)
library(RWeka)
library(tm)
library(caret)
library(lubridate)
library(mice)
library(RODBC) #database connection

# All variable names dependent on local data structure!

###########
#Read Data#
###########
#read provider data (the example below uses a database connection through SQL using the RODBC library)
options(stringsAsFactors = FALSE)
cn <-odbcDriverConnect(connection=...;server=...;database=...;trusted_connection=yes;")
provs <- sqlQuery(cn,"select * from ...")
names(provs)[1]<-"MPOG_Case_ID"  #can be replaced with local case ID

#get primary surgeon id
getsurgid<-provs %>%
  filter(MPOG_Staff_Role_Concept_ID==6006) %>%
  group_by(MPOG_Case_ID) %>%
  slice(1) %>%
  rename(surgid=AIMS_Staff_ID)  #can be replaced with local staff ID

#get primary anes id
getanesid<-provs %>%
  filter(MPOG_Staff_Role_Concept_ID==6000) %>%
  group_by(MPOG_Case_ID) %>%
  slice(1) %>%
  rename(anesid=AIMS_Staff_ID)

#read cases (the example below reads data from a CSV)
setwd("C:/...") #set your working directory to the location of your data
cases<-read.csv(“your_case_data”)
names(cases)[1]<-"MPOG_Case_ID"

#add surgeon and anes id to cases
cases<-merge(cases,getsurgid,by="MPOG_Case_ID")
cases<-merge(cases,getanesid,by="MPOG_Case_ID")
cases$Date<-as.Date(cases$Anesthesia.Start)

#separate Anesthesia CPTs into separate columns
#Anesthesia CPT generated by prediction model
cases<-cases %>% separate(Predicted.Anes.CPTs, c("CPT1","CPT2","CPT3"),extra="drop")

#convert duration variable to numeric format
cases$Patient.In.Room.Duration<-as.numeric(as.character(cases$Patient.In.Room.Duration))

#exclude case length NA, negative, or greater than 1440 minutes
cases<-cases %>%
  filter(!is.na(Patient.In.Room.Duration)) %>%
  filter(Patient.In.Room.Duration>0) %>%
  filter(Patient.In.Room.Duration<1440)

#################################################################
####Below code is for monthly engineered experience features
#################################################################

#--Below code is only for monthly engineered experience features
firstdate=min(cases$Date)
lastdate=max(cases$Date)

rangebymonth=seq(firstdate,lastdate,by="month")

cases<-cases %>%
  mutate(surgtotexp=0) %>%
  mutate(surgcaseexp=0) %>%
  mutate(instcaseexp=0) %>%
  mutate(histcaselength=0) %>%
  mutate(histcaseinst=0) %>%
  mutate(histcasesurg=0) %>%
  mutate(surgtotdensity=0) %>%
  mutate(surgcasedensity=0) %>%
  mutate(instcasedensity=0)

cases<-cases %>%
  group_by(surgid) %>%
  mutate(surgfirstdate=min(Date)) %>%
  ungroup()

cases<-cases %>%
  group_by(Institution) %>%
  mutate(instfirstdate=min(Date)) %>%
  ungroup()
  
system.time(
for(x in 1:(length(rangebymonth)-1)){

newdatestart=rangebymonth[x]
newdateend=rangebymonth[x+1]
  
surgtotexpt<-cases %>%
  filter(between(Date,firstdate,newdateend)) %>%
  count(surgid, name="surgtotexp")

surgcaseexpt<-cases %>%
  filter(between(Date,firstdate,newdateend)) %>%
  count(surgid, CPT1,name="surgcaseexp")

instcaseexpt<-cases %>%
  filter(between(Date,firstdate,newdateend)) %>%
  group_by(Institution,CPT1) %>%
  count(CPT1, Institution,name="instcaseexp") %>%
  ungroup()

#hist case length
histcaselength<-cases %>%
  filter(between(Date,firstdate,newdateend)) %>%
  group_by(CPT1) %>%
  summarize(histcaselength=mean(Patient.In.Room.Duration,na.rm=TRUE))

#hist case length by inst
histcaseinstt<- cases %>%
  filter(between(Date,firstdate,newdateend)) %>%
  group_by(Institution,CPT1) %>%
  summarize(histcaseinst=mean(Patient.In.Room.Duration,na.rm=TRUE))

#hist case length by surgeon
histcasesurgt<- cases %>%
  filter(between(Date,firstdate,newdateend)) %>%
  group_by(surgid, CPT1) %>%
  summarize(histcasesurg=mean(Patient.In.Room.Duration,na.rm=TRUE))

newcases<-cases %>%
  filter(Date>=newdatestart) %>%
  select(-c(surgtotexp,surgcaseexp,instcaseexp,histcaselength,histcaseinst,histcasesurg,surgtotdensity,surgcasedensity,instcasedensity)) %>%
  left_join(surgtotexpt,by="surgid") %>%
  left_join(surgcaseexpt,by=c("surgid","CPT1")) %>%
  left_join(histcasesurgt,by=c("surgid","CPT1"))%>%
  left_join(instcaseexpt,by=c("Institution","CPT1"))%>%
  left_join(histcaselength,by="CPT1") %>%
  left_join(histcaseinstt,by=c("Institution","CPT1")) %>%
  mutate(surgtotdensity=surgtotexp/as.numeric(newdateend-surgfirstdate)) %>%
  mutate(surgcasedensity=surgcaseexp/as.numeric(newdateend-surgfirstdate)) %>%
  mutate(instcasedensity=instcaseexp/as.numeric(newdateend-instfirstdate)) %>%
  bind_rows(cases[(cases$Date>=firstdate & cases$Date<newdatestart),])

cases<-newcases
}
)

#eliminate NA for engineered features
cases$surgtotexp[which(is.na(cases$surgtotexp))]<-0
cases$surgcaseexp[which(is.na(cases$surgcaseexp))]<-0
cases$instcaseexp[which(is.na(cases$instcaseexp))]<-0
cases$histcaselength[which(is.na(cases$histcaselength))]<-0
cases$histcaseinst[which(is.na(cases$histcaseinst))]<-0
cases$histcasesurg[which(is.na(cases$histcasesurg))]<-0

#################################################################
####Above code is for monthly engineered experience features
#################################################################


#################
#Natural Language Processing
#################
tokenizer <- function(x) {
  NGramTokenizer(x, Weka_control(min = 1, max = 2))
}
review_corpus = VCorpus(VectorSource(cases$Scheduled.Procedure))
review_corpus = tm_map(review_corpus, content_transformer(tolower))
review_corpus = tm_map(review_corpus, removeWords, c("the", "and", "w", "with", "(actual)", "phi","wrvu","right","left","nbb","endo",stopwords("english")))
replacePunctuation <- content_transformer(function(x) {return (gsub("[[:punct:]]"," ", x))})
removeDash <- content_transformer(function(x) {return (gsub("-","", x))})
review_corpus = tm_map(review_corpus, removeDash)
review_corpus = tm_map(review_corpus, replacePunctuation)
review_corpus =  tm_map(review_corpus, stripWhitespace)
expandIOL <- content_transformer(function(x) {return (gsub("iol","intraocular lens", x))})
expandCSection <- content_transformer(function(x) {return (gsub("csection","cesarean section", x))})
expandEGD <- content_transformer(function(x) {return (gsub("egd","esophagogastroduodenoscopy", x))})
expandcath <- content_transformer(function(x) {return (gsub("\\bcath\\b","catheter", x))})
expandcysto <- content_transformer(function(x) {return (gsub("\\bcysto\\b","cystoscopy", x))})
review_corpus = tm_map(review_corpus, expandIOL)
review_corpus = tm_map(review_corpus, expandCSection)
review_corpus = tm_map(review_corpus, expandEGD)
review_corpus = tm_map(review_corpus, expandcath)
review_corpus = tm_map(review_corpus, expandcysto)

inspect(review_corpus[1])
tokenize=tokenizer
review_dtm_tfidf <- DocumentTermMatrix(review_corpus, control = list(weighting=weightTfIdf, tokenize=tokenizer))
review_dtm_tfidf = removeSparseTerms(review_dtm_tfidf, 0.995)

z<-as.matrix(review_dtm_tfidf)

#class conversions
cases$BMI<-as.numeric(as.character(cases$BMI))
cases$Age..Years.<-as.numeric(cases$Age..Years.)
cases$Height<-as.numeric(as.character(cases$Height))
cases$Weight<-as.numeric(as.character(cases$Weight))
#cases$Preop.Creatinine<-as.numeric(as.character(cases$Preop.Creatinine))
#cases$Preop.Hemoglobin<-as.numeric(as.character(cases$Preop.Hemoglobin))
#cases$Preop.Albumin<-as.numeric(as.character(cases$Preop.Albumin))
#cases$Preop.INR<-as.numeric(as.character(cases$Preop.INR))
cases$Institution<-as.factor(cases$Institution)

#convert NULL CPT to 00000
cases$CPT1[which(cases$CPT1=="NULL")]<-"00000"

cases$ASA.Class[which(cases$ASA.Class=="NULL")]<-"-999"
cases$timeofday<-lubridate::hour(as.POSIXct(cases$Anesthesia.Start))


#create data frames to include all relevant variables and NLP matrix
## to run below, you must run the monthly engineered experience features in the above section
atOR<-data.frame(Patient.In.Room.Duration=cases$Patient.In.Room.Duration,surgid=cases$surgid,anesCPT=cases$CPT1,inst=cases$Institution,admittype=cases$Admission.Type,gender=cases$Gender,race=cases$Race,age=cases$Age..Years.,height=cases$Height,weight=cases$Weight,BMI=cases$BMI,ASA=cases$ASA.Class,basemap=cases$Baseline.MAP,emergency=cases$Emergency.Status,holiday=cases$Holiday,weekend=cases$Weekend,service=cases$Surgical.Service,roomtype=cases$Procedure.Room.Type,cardiac=cases$Cardiac.Procedure,anesgen=cases$Anes.Tech.General,creatinine=cases$Preop.Creatinine,hgb=cases$Preop.Hemoglobin,albumin=cases$Preop.Albumin,inr=cases$Preop.INR,CHF=cases$Elixhauser..Congestive.Heart.Failure,arrhythmia=cases$Elixhauser..Cardiac.Arrhythmia,valve=cases$Elixhauser..Valvular.Disease,pvd=cases$Elixhauser..Peripheral.Vascular.Disorders,htncomp=cases$Elixhauser..Hypertension.with.Complications,htnnocomp=cases$Elixhauser..Hypertension.without.Complications,dmcomp=cases$Elixhauser..Diabetes.with.Complications,dmnocomp=cases$Elixhauser..Diabetes.without.Complications,pulm=cases$Elixhauser..Chronic.Pulmonary.Disease,renal=cases$Elixhauser..Renal.Failure,timeofday=cases$timeofday,surgtotexp=cases$surgtotexp,surgcaseexp=cases$surgcaseexp,instcaseexp=cases$instcaseexp,histcaselength=cases$histcaselength,histcaseinst=cases$histcaseinst,histcasesurg=cases$histcasesurg,surgtotdensity=cases$surgtotdensity,surgcasedensity=cases$surgcasedensity,instcasedensity=cases$instcasedensity,z)
#visualize missing data
md.pattern(atOR) #missing data pattern from mice library

atsched<-data.frame(Patient.In.Room.Duration=cases$Patient.In.Room.Duration,surgid=cases$surgid,anesCPT=cases$CPT1,inst=cases$Institution,admittype=cases$Admission.Type,gender=cases$Gender,race=cases$Race,age=cases$Age..Years.,height=cases$Height,weight=cases$Weight,BMI=cases$BMI,ASA=cases$ASA.Class,holiday=cases$Holiday,weekend=cases$Weekend,service=cases$Surgical.Service,roomtype=cases$Procedure.Room.Type,cardiac=cases$Cardiac.Procedure,CHF=cases$Elixhauser..Congestive.Heart.Failure,arrhythmia=cases$Elixhauser..Cardiac.Arrhythmia,valve=cases$Elixhauser..Valvular.Disease,pvd=cases$Elixhauser..Peripheral.Vascular.Disorders,htncomp=cases$Elixhauser..Hypertension.with.Complications,htnnocomp=cases$Elixhauser..Hypertension.without.Complications,dmcomp=cases$Elixhauser..Diabetes.with.Complications,dmnocomp=cases$Elixhauser..Diabetes.without.Complications,pulm=cases$Elixhauser..Chronic.Pulmonary.Disease,renal=cases$Elixhauser..Renal.Failure,timeofday=cases$timeofday,surgtotexp=cases$surgtotexp,surgcaseexp=cases$surgcaseexp,instcaseexp=cases$instcaseexp,histcaselength=cases$histcaselength,histcaseinst=cases$histcaseinst,histcasesurg=cases$histcasesurg,surgtotdensity=cases$surgtotdensity,surgcasedensity=cases$surgcasedensity,instcasedensity=cases$instcasedensity,z)
atincis<-data.frame(Patient.In.Room.Duration=cases$Patient.In.Room.Duration,surgid=cases$surgid,anesCPT=cases$CPT1,inst=cases$Institution,admittype=cases$Admission.Type,gender=cases$Gender,race=cases$Race,age=cases$Age..Years.,height=cases$Height,weight=cases$Weight,BMI=cases$BMI,ASA=cases$ASA.Class,basemap=cases$Baseline.MAP,emergency=cases$Emergency.Status,holiday=cases$Holiday,weekend=cases$Weekend,service=cases$Surgical.Service,roomtype=cases$Procedure.Room.Type,cardiac=cases$Cardiac.Procedure,creatinine=cases$Preop.Creatinine,hgb=cases$Preop.Hemoglobin,albumin=cases$Preop.Albumin,inr=cases$Preop.INR,CHF=cases$Elixhauser..Congestive.Heart.Failure,arrhythmia=cases$Elixhauser..Cardiac.Arrhythmia,valve=cases$Elixhauser..Valvular.Disease,pvd=cases$Elixhauser..Peripheral.Vascular.Disorders,htncomp=cases$Elixhauser..Hypertension.with.Complications,htnnocomp=cases$Elixhauser..Hypertension.without.Complications,dmcomp=cases$Elixhauser..Diabetes.with.Complications,dmnocomp=cases$Elixhauser..Diabetes.without.Complications,pulm=cases$Elixhauser..Chronic.Pulmonary.Disease,renal=cases$Elixhauser..Renal.Failure,timeofday=cases$timeofday,artline=cases$Aterial.Line,anestime=cases$Anesthesia.Duration,block=cases$Anes.Tech.Block,epid=cases$Anes.Tech.Epidural,genanes=cases$Anes.Tech.General,lma=cases$Anes.Tech.LMA,neurax=cases$Anes.Tech.Neuraxial,spinal=cases$Anes.Tech.Spinal,surgtotexp=cases$surgtotexp,surgcaseexp=cases$surgcaseexp,instcaseexp=cases$instcaseexp,histcaselength=cases$histcaselength,histcaseinst=cases$histcaseinst,histcasesurg=cases$histcasesurg,surgtotdensity=cases$surgtotdensity,surgcasedensity=cases$surgcasedensity,instcasedensity=cases$instcasedensity,z)


#################
#Save the processed data
#################
setwd("C:/...") #set your working directory to the location you want to save your files
write.csv(atsched, 'atsched.csv', row.names = FALSE)
write.csv(atOR, 'atOR.csv', row.names = FALSE)
write.csv(atincis, 'atincis.csv', row.names = FALSE)
